build_image:
  stage: build
  script:
    - docker build --no-cache -t myimage .

scan_image:
  before_script:
    - docker network create scanning
    - docker run -p 5432:5432 -d --net=scanning --name db arminc/clair-db:2017-09-18; sleep 30
    - docker run -p 6060:6060  --net=scanning --link db:postgres -d --name clair arminc/clair-local-scan:v2.0.6 ; sleep 30
  script:
    - docker run --net=scanning --rm --name=scanner --link=clair:clair -v '/var/run/docker.sock:/var/run/docker.sock' objectiflibre/clair-scanner --clair="http://clair:6060" --ip="scanner" -t Medium myimage || true
    - docker tag myimage 192.168.2.2:5000/myimage
    - docker push 192.168.2.2:5000/myimage
  after_script:
    - docker rm -vf db clair
    - docker network rm scanning

