- name: Pull and run the necessary images for clair-scanner
  hosts: "gitlab"
  
  tasks:
  - name: pull exe
    become: yes
    shell: docker pull objectiflibre/clair-scanner

  - name: pull db
    become: yes
    shell: docker pull arminc/clair-db:2017-09-18

  - name: pull scanner
    become: yes
    shell: docker pull arminc/clair-local-scan:v2.0.6
