- name: register the runner
  hosts: "gitlab"
  
  tasks:

  - name: Téléchargement
    become: yes
    shell: wget -O /usr/local/bin/gitlab-runner http://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-linux-amd64
    
  - name: install de gitlab-runner
    become: yes
    shell: chmod +x /usr/local/bin/gitlab-runner

  - name: install de gitlab-runner
    become: yes
    shell: useradd --comment 'GitLab Runner' --create-home gitlab-runner --shell /bin/bash

  - name: install de gitlab-runner
    become: yes
    shell: gitlab-runner install --user=gitlab-runner --working-directory=/home/gitlab-runner

  - name: install de gitlab-runner
    become: yes
    shell: gitlab-runner start

